# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py

Exception: File `'initialise.py'` not found.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
print(np.show_config)

1.19.2
<function show at 0x000002823899C310>


#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [18]:
null_vector.itemsize

8

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [23]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [24]:
null_vector[4] =1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
vector_reverse = np.arange(10,50)[::-1]
print(vector_reverse)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
a = np.arange(0,9)
a_1 = a.reshape(3,3)
print(a_1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [29]:
b = np.nonzero([1,2,0,0,4,0])
b


(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [15]:
c = np.array([1,0,0,0,1,0,0,0,1]).reshape(3,3)
print(c)    #np.identity(3)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [30]:
np.random.random((3,3,3))


array([[[0.94176402, 0.49495444, 0.35859648],
        [0.76897844, 0.07765494, 0.75009469],
        [0.97378042, 0.57632834, 0.7696837 ]],

       [[0.05109656, 0.75935604, 0.16330227],
        [0.41973196, 0.90439825, 0.59855374],
        [0.34336502, 0.87411449, 0.68091212]],

       [[0.10280207, 0.7570421 , 0.38404708],
        [0.72660409, 0.21145111, 0.55270149],
        [0.26769088, 0.40292068, 0.76753081]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [36]:
z= np.random.random((10,10))
print(z)
print(z.min())
print(z.max())

[[0.4931988  0.61254407 0.09572344 0.76781751 0.57135403 0.63221029
  0.09632991 0.08918995 0.95277655 0.75803921]
 [0.25703781 0.78942915 0.34839972 0.13059241 0.13399387 0.99578838
  0.29882449 0.64866369 0.40529145 0.41309976]
 [0.32086123 0.32447255 0.12344723 0.79432809 0.99208235 0.31260945
  0.31427951 0.79976286 0.76833733 0.35498903]
 [0.79169899 0.50027023 0.76611136 0.18184859 0.26284754 0.97448637
  0.37961045 0.19827473 0.90189886 0.90970967]
 [0.14263674 0.98011377 0.38321973 0.50167021 0.78125838 0.53966311
  0.61966059 0.46300006 0.03321006 0.5432638 ]
 [0.6638428  0.91261892 0.09945623 0.011786   0.39594    0.7126195
  0.08191225 0.36369559 0.37364544 0.42079292]
 [0.32863872 0.2861326  0.59819344 0.2124691  0.4871186  0.78951492
  0.44579011 0.06877687 0.7423424  0.96155673]
 [0.24184294 0.64938952 0.75724233 0.76353921 0.9699656  0.66626637
  0.10397316 0.14486333 0.57785685 0.82942387]
 [0.79650075 0.22102712 0.19611357 0.12619344 0.39965898 0.27029511
  0.34232768 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [37]:
z= np.random.random((30))
print(z)
print(z.mean())

[0.29028081 0.5208899  0.88563184 0.96925461 0.12969834 0.88295517
 0.0932146  0.7785166  0.06400581 0.95044997 0.35822608 0.82494507
 0.38611341 0.79709095 0.14965715 0.25746294 0.28243119 0.59157735
 0.1483714  0.89536171 0.64468172 0.74569822 0.9982341  0.18770147
 0.81422573 0.99004765 0.07392234 0.1941595  0.20689204 0.58764664]
0.5233114774374151


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [44]:
a=np.zeros((3,3))
a[[0,-1]]=1
a[:,[0,-1]]=1
print(a)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 1

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [50]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)   # 3*0.1 값이 정확하게 나오지 않아 

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [51]:
z= np.diag(np.arange(1,5),k=-1)  #np.diag():대각행렬만들기
z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [53]:
x = np.zeros((8,8),dtype = int)
x
x[1::2,::2] = 1
x[::2,1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
print (np.unravel_index(100, (6,7,8)))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
array= np.array([[0,1], [1,0]])
Z = np.tile(array,(4,4))
print (Z)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
Z= np.dot(np.ones((5,3)), np.ones((3,2)))
print (Z)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [45]:
x = np.arange(11)
x[(x >= 3) & (x <= 8)] = -1

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [46]:
print(sum(range(5), -1))  # 9
from numpy import *

print(sum(range(5), -1))  # 10

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [47]:
Z = np.arange(3)
Z ** Z       # = [0^0, 1^1, 2^2] = [1, 1, 4]
2 << Z >> 2  # = [0, 1, 2]
Z < - Z      # = [False, False, False]
1j * Z       # = [0 + 0.j, 0 + 1.j, 0 + 2.j]
Z / 1 / 1    # = [0, 1, 2]
Z < Z > Z    # ValueError

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

#### 29. How to round away from zero a float array ? (★☆☆)

In [48]:
x = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(x)), x)


array([ -8.,  -3.,   1.,   9.,  -3., -10.,   5.,   5.,   4.,  -6.])

#### 30. How to find common values between two arrays? (★☆☆)

In [49]:
x = np.arange(0, 10)
y = np.arange(5, 15)
np.intersect1d(x, y)


array([5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [50]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [52]:
print(np.sqrt(-1) == np.emath.sqrt(-1))  # False

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [53]:
today = np.datetime64('today', 'D')
yesterday = today - np.datetime64(1, 'D')
tomorrow = today + np.datetime64(1, 'D')


UFuncTypeError: ufunc 'add' cannot use operands with types dtype('<M8[D]') and dtype('<M8[D]')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [54]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [41]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [40]:
x = np.random.uniform(-10, +10, 10)
x.astype(np.int32)
np.trunc(x)

array([-0., -4.,  1.,  2.,  6., -6.,  1.,  4.,  3.,  2.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [42]:
x = np.zeros((5, 5))
x += np.arange(5)


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate_integers():
    for i in range(10):
        yield i
np.fromiter(generate_integers(), dtype=np.float32, count=-1)


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [6]:
z=np.linspace(0,1,11,endpoint=False)[1:]
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [12]:
z=np.random.random(10)
z.sort()
print(z)

[0.05733827 0.11100958 0.18830999 0.22140962 0.57563668 0.72697414
 0.77569819 0.79349624 0.81041827 0.97178007]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [13]:
Z=np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [15]:
a=np.random.random(0,10,5)
b=np.random.random(0,10,5)
print(np.allclose(a,b))

TypeError: random() takes at most 1 positional argument (3 given)

#### 43. Make an array immutable (read-only) (★★☆)

In [16]:
x = np.zeros(10)
x.flags.writeable = False
x[1] = 1   # ValueError: assignment destination is read-only

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [17]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.28613996 0.28976754 0.05629532 0.8006537  0.30720105 0.92670836
 0.69004838 1.06882781 1.20419202 0.92417602]
[0.45190156 0.73588684 0.99102565 0.48944247 1.43670493 1.11955825
 1.44119189 0.67322944 0.85644704 1.1417769 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [18]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.77268457 0.39100004 0.88727805 0.06990733 0.36972978 0.
 0.44140979 0.02671975 0.82737196 0.70540804]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [19]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [43]:
x = np.random.random((5, 5))
y = np.random.random((5, 5))
c = 1 / (x - y)
c = 1 / np.subtract.outer(x, y)
np.linalg.det(c)

array([[ -132342.82685374,    38872.39758447, -2366953.81496122,
         -143689.11473088,  -116863.5146815 ],
       [ -176893.88610042,     9754.93648538,   -33367.57058813,
         -113585.32837397,  -208604.49030296],
       [ -618142.03268653,  -112586.98057484,   -91841.21949136,
         5679345.3782538 ,   492657.06938697],
       [ -270512.28763388,  2370388.59969476,  -847417.51840566,
           81880.67189532,  -248651.11219042],
       [    8631.02776501,   -95086.46414278,  -321297.06255778,
          333408.05480152,   -84451.09107553]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [20]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [44]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((25,25))
print(Z)

ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [22]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

50


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [23]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-23-3a6f5eca1821>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [24]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.99926937 0.14338871 0.98601337 0.60143044 0.91523554
  0.41373107 0.68530761 0.31411112 0.66695279]
 [0.99926937 0.         0.85713729 0.13594709 0.64655569 0.44838753
  0.60744558 0.44736423 0.7335561  0.51936296]
 [0.14338871 0.85713729 0.         0.84820504 0.51107041 0.78163616
  0.28516473 0.56453755 0.1859839  0.55618031]
 [0.98601337 0.13594709 0.84820504 0.         0.55920521 0.56693504
  0.57702707 0.36443341 0.75009005 0.43006518]
 [0.60143044 0.64655569 0.51107041 0.55920521 0.         0.85689127
  0.27935052 0.19919341 0.55070903 0.12916392]
 [0.91523554 0.44838753 0.78163616 0.56693504 0.85689127 0.
  0.6617284  0.69391875 0.60113736 0.76219614]
 [0.41373107 0.60744558 0.28516473 0.57702707 0.27935052 0.6617284
  0.         0.28097446 0.2741368  0.28315769]
 [0.68530761 0.44736423 0.56453755 0.36443341 0.19919341 0.69391875
  0.28097446 0.         0.53599873 0.07419277]
 [0.31411112 0.7335561  0.1859839  0.75009005 0.55070903 0.60113736
  0.2741368  0.535998

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [25]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [26]:
Z = np.genfromtxt("missing.dat", delimiter=",")

OSError: missing.dat not found.

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [39]:
a = np.array([[1, 2], [3, 4]])
for index, x in np.ndenumerate(a):
    print(index, x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [27]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [28]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [29]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)
Y

array([[ 0.06078542, -0.11332906,  0.24255423,  0.15653779, -0.46067402,
         0.21630844, -0.0112975 , -0.13699767, -0.37440096,  0.42051334],
       [ 0.33352077,  0.12518013, -0.42961253, -0.35745872,  0.54833024,
        -0.04395073,  0.0704879 , -0.35272571,  0.29884886, -0.19262022],
       [-0.11024308, -0.22453254,  0.13164887,  0.25991737,  0.28382095,
         0.04428136, -0.17107234, -0.19363773, -0.18660191,  0.16641905],
       [ 0.0599884 ,  0.40199815,  0.48859469, -0.31022838, -0.42913777,
        -0.31412159,  0.09878481,  0.30471699,  0.10622017, -0.40681547],
       [-0.34969851,  0.19141867,  0.01609726, -0.31022708,  0.07433803,
         0.03102574,  0.0892775 , -0.0915652 ,  0.09614506,  0.25318853]])

#### 59. How to sort an array by the nth column? (★★☆)

In [30]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[5 6 7]
 [3 5 1]
 [5 7 9]]
[[3 5 1]
 [5 6 7]
 [5 7 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [31]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())


True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [32]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)


0.46656403487619147


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [38]:
a=np.array(3).reshape(3,1)
b=np.array(3).reshape(3,1)
iterator=np.nditer([a,b,None])

for x,y,z in iterator:
    z=x+y
print(iterator.operands[2])

ValueError: cannot reshape array of size 1 into shape (3,1)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [33]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)


[6. 3. 3. 2. 2. 2. 2. 6. 3. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [34]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [35]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)