# **1. 규제 선형 회귀 모델/ 회귀 트리**
릿지 회귀모델 및 회귀 트리를 이용하여 전복의 나이를 예측해 보세요.

전복의 ‘성별’, ‘키’, ‘지름’, ‘높이’, ‘전체무게’, ‘몸통무게’, ‘내장무게’, ‘껍질무게’를 입력하면 ‘껍질의 고리수’를 예측한 뒤 예측된 ‘껍질의 고리수’에 1.5를 더하면 전복의 나이가 됩니다.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import os
os.chdir('/content/drive/MyDrive/ESAA/회귀')

In [3]:
os.getcwd()

'/content/drive/MyDrive/ESAA/회귀'

In [4]:
# 기본 모듈 불러오기
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings(action='ignore')

### 1) 데이터 불러오기 및 데이터 선택

In [7]:
# 데이터 로드
data = pd.read_csv("abalone.csv")

# 성별 M은 Male, F는 Female, I는 Infant 이므로 따로 열 만들기
for label in "MFI":
    data[label] = data["Sex"] == label
data.drop('Sex', axis=1, inplace=True)

# X,y 데이터 선택
y = data.Rings.values
data.drop('Rings', axis=1, inplace=True)

X = data.values.astype(float)

## 2) train/test 분리
: 테스트 셋과 데이터 셋을 7:3 비율로 분리하세요.

In [9]:
# 필요한 모듈 불러오기
from sklearn.model_selection import train_test_split

In [10]:
# train과 test set 분리 (train:test = 7:3 비율로)
X_train,X_test,y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=0)

## 3) 릿지 모델을 이용한 모델링
: 릿지 모델을 이용하여 전복의 나이를 예측해 보고 결과를 평가해 보세요.

 3-1) 릿지모델 생성, 교차검증, 평가에 필요한 모듈을 불러오세요.

In [11]:
#필요한 모듈 불러오기
from sklearn.linear_model import Ridge
from sklearn.model_selection import cross_val_score

3-2) 릿지 모델을 생성하고 훈련하여 MSE와 RMSE를 구하세요. 릿지 모델 생성 시  alpha는 0.3으로 설정합니다. (교차 검증 하지 않습니다.)

In [12]:
#릿지모델 생성 및 훈련
ridge = Ridge(alpha=0.3)
ridge.fit(X_train,y_train)
#예측값 구하기
pred_ridge = ridge.predict(X_test)

#MSE와 RMSE구하기
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test,pred_ridge)
rmse = np.sqrt(mse)

In [13]:
mse

5.013158686100955

In [14]:
rmse

2.239008415817358

3-3) 교차검증을 이용하여 0, 0.1, 1, 10, 100 중  모델 성능이 가장 좋게 나오는 (rmse가 최소가 되는) alpha를 구하세요. 

In [16]:
# 주어진 alpha
alphas=[0, 0.1, 1, 10, 100]

In [20]:
#alphas list 값을 반복하면서 alpha에 따른 평균 rmse를 구함
for alpha in alphas:
    ridge = Ridge(alpha=alpha)
    neg_mse_scores = cross_val_score(ridge,X_train,y_train,scoring='neg_mean_squared_error',cv=5)
    avg_rmse = np.mean(np.sqrt(-1*neg_mse_scores))
    print('alpha {} 평균 rmse:{}'.format(alpha,avg_rmse))

#cross_val_score를 이용해 5 폴드의 평균 RMSE를 계산


alpha 0평균 rmse:2.1921123092358794
alpha 0.1평균 rmse:2.188965384248428
alpha 1평균 rmse:2.1920430964820867
alpha 10평균 rmse:2.3359968157278956
alpha 100평균 rmse:2.604249483579334


In [25]:
neg_mse_scores

array([-6.22911191, -6.46878871, -6.42984771, -7.72308579, -7.11442901])

## 4) XGBRegressor을 이용한 모델링
: XGBRegressor 모델을 이용하여 전복의 나이를 예측해 보고 결과를 평가해 보세요.

4-1) XGBRegressor 훈련, 평가에 필요한 모듈을 불러오세요.

In [21]:
# 필요한 모듈 임포트
from xgboost import XGBRegressor

4-2) XGBregressor 모델을 생성하고 훈련하여 MSE와 RMSE를 구하세요.

In [22]:
#모델 생성 및 훈련
xgb_reg = XGBRegressor(n_estimators=1000)
xgb_reg.fit(X_train,y_train)
#예측값 구하기
pred_xgb = xgb_reg.predict(X_test)

#MSE와 RMSE 구하기
mse = mean_squared_error(y_test,pred_xgb)
rmse = np.sqrt(mse)


[09:54:35] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


In [23]:
mse

5.337108949877299

In [24]:
rmse

2.3102183770971303

# **2. 로지스틱 회귀분석**
load_wine() 함수를 이용하여 와인 데이터를 다항분류하는 로지스틱 회귀모델을 생성하세요. 

In [26]:
# 필요한 모듈 불러오기
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

# 1) 데이터 불러오기 및 변수 선택

In [27]:
wine = load_wine()

wine_x = wine.data # x변수 
wine_y = wine.target # y변수

In [51]:
wine

{'DESCR': '.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- Alcohol\n \t\t- Malic acid\n \t\t- Ash\n\t\t- Alcalinity of ash  \n \t\t- Magnesium\n\t\t- Total phenols\n \t\t- Flavanoids\n \t\t- Nonflavanoid phenols\n \t\t- Proanthocyanins\n\t\t- Color intensity\n \t\t- Hue\n \t\t- OD280/OD315 of diluted wines\n \t\t- Proline\n\n    - class:\n            - class_0\n            - class_1\n            - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80    2.34  1.12\n    Ash:           

# 2) train/test 셋 분리

In [28]:
x_train, x_test, y_train, y_test = train_test_split(wine_x, wine_y, test_size=0.3, random_state=123)

x_train.shape 
y_train.shape 

(124,)

In [33]:
x_train.shape

(124, 13)

In [37]:
y_train

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 1, 0, 1, 2, 0, 0, 0, 2,
       1, 1, 1, 2, 0, 0, 1, 1, 1, 2, 2, 0, 2, 2, 2, 2, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 2, 0, 2, 0, 0, 2, 1, 2, 0, 0, 1, 0,
       2, 1, 1, 0, 0, 1, 0, 1, 2, 1, 0, 0, 0, 1, 1, 1, 2, 2, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 1, 0, 0, 0, 1, 2, 1, 2, 2, 1, 0,
       1, 0, 2, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1])

In [39]:
y_train.shape

(124,)

# 3) 로지스틱 회귀모델을 이용한 모델링

3-1) 로지스틱 회귀모델을 생성하여 훈련하세요.

In [29]:
lr_clf = LogisticRegression()
lr_clf.fit(x_train,y_train)

LogisticRegression()

3-2) 회귀 모델의 기울기와 절편을 구하세요.

In [36]:
#기울기
lr_clf.coef_

array([[-1.99751167e-01,  3.65450552e-01,  1.49472112e-01,
        -1.88027149e-01, -2.28495646e-02,  1.95456485e-01,
         4.66701265e-01, -1.66796661e-02,  8.23897101e-02,
         6.75011473e-02, -1.92621856e-02,  2.94915749e-01,
         7.42524049e-03],
       [ 5.96475829e-01, -7.88672591e-01, -1.26181429e-01,
         2.12254654e-01, -1.13504800e-02,  3.15785912e-01,
         3.55147976e-01,  3.34675580e-02,  2.79035669e-01,
        -1.17202474e+00,  2.61165677e-01,  4.64731544e-01,
        -8.33633158e-03],
       [-3.96724662e-01,  4.23222039e-01, -2.32906833e-02,
        -2.42275051e-02,  3.42000446e-02, -5.11242396e-01,
        -8.21849241e-01, -1.67878919e-02, -3.61425379e-01,
         1.10452359e+00, -2.41903492e-01, -7.59647293e-01,
         9.11091084e-04]])

In [38]:
#절편
lr_clf.intercept_

array([-0.04177837,  0.09551046, -0.05373209])

3-3) 모델의 정확도를 구하세요.

In [43]:
#모델의 예측값 구하기
lr_preds = lr_clf.predict(x_test)

#모델의 정확도 구하기
from sklearn.metrics import accuracy_score
print('accuracy:',accuracy_score(y_test,lr_preds))


accuracy: 0.9629629629629629


In [45]:
lr_preds

array([2, 1, 2, 1, 1, 2, 0, 2, 2, 1, 2, 2, 2, 0, 0, 2, 1, 1, 0, 1, 2, 2,
       2, 2, 1, 2, 2, 1, 0, 0, 0, 0, 2, 1, 2, 1, 1, 0, 1, 1, 2, 2, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 2, 2, 1])

In [46]:
lr_clf.predict_proba(x_test)

array([[3.62741883e-02, 2.48449022e-02, 9.38880909e-01],
       [1.38758318e-01, 7.77202273e-01, 8.40394093e-02],
       [1.31091840e-02, 2.73796758e-02, 9.59511140e-01],
       [1.92986784e-02, 9.60265573e-01, 2.04357486e-02],
       [2.83510406e-03, 9.96817328e-01, 3.47567444e-04],
       [4.96645798e-04, 3.47296880e-06, 9.99499881e-01],
       [9.95724987e-01, 2.03159255e-03, 2.24342089e-03],
       [1.41333932e-01, 1.52855795e-02, 8.43380488e-01],
       [1.38839399e-04, 1.34960855e-07, 9.99861026e-01],
       [2.34805155e-04, 9.99758737e-01, 6.45752804e-06],
       [2.70873737e-03, 6.74344846e-04, 9.96616918e-01],
       [1.78709484e-01, 2.05903455e-02, 8.00700170e-01],
       [5.59758857e-04, 1.46113205e-05, 9.99425630e-01],
       [9.87919256e-01, 8.54821165e-04, 1.12259226e-02],
       [9.98901258e-01, 8.25609009e-07, 1.09791638e-03],
       [8.45904785e-04, 7.65566848e-02, 9.22597410e-01],
       [1.11735900e-03, 9.98846522e-01, 3.61186531e-05],
       [1.53275472e-04, 9.99804

In [47]:
lr_clf_1 = LogisticRegression(multi_class='ovr')
lr_clf_1.fit(x_train,y_train)

LogisticRegression(multi_class='ovr')

In [48]:
pred_1 = lr_clf_1.predict(x_test)

In [49]:
pred_1

array([2, 1, 2, 1, 1, 2, 0, 2, 2, 1, 2, 2, 2, 0, 0, 2, 1, 1, 0, 1, 2, 2,
       2, 2, 1, 2, 2, 0, 0, 0, 0, 0, 2, 1, 2, 1, 1, 0, 1, 1, 2, 2, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 2, 2, 1])

In [50]:
lr_clf_1.coef_

array([[-8.41589135e-01,  9.82319587e-01,  8.09112711e-01,
        -5.45118541e-01,  8.18055963e-03,  1.55363240e-01,
         1.34632965e+00,  9.85998824e-02, -3.80839383e-01,
        -1.00232506e-01, -1.20943318e-01,  6.28136102e-01,
         1.56585961e-02],
       [ 9.29497419e-01, -1.38449182e+00, -3.14677559e-01,
         2.91927144e-01, -1.38195420e-02,  2.91125780e-01,
         2.38126891e-01,  1.14211415e-01,  4.05918631e-01,
        -1.54540569e+00,  4.75825140e-01,  3.94155919e-01,
        -1.32905037e-02],
       [-3.89167432e-01,  6.42165615e-01,  4.17279360e-02,
         1.05782831e-01,  3.47763992e-02, -7.67526934e-01,
        -1.43627194e+00, -1.93958031e-01, -7.20745113e-01,
         9.19915064e-01, -5.60638280e-01, -1.14137223e+00,
        -1.98488541e-04]])

In [ ]:
lr_clf = LogisticRegression(solver ='lbfgs', multi_class='multinomial')
