#CHAPTER 9 비지도 학습

##9.1 군집

###9.1.1 K-평균 

**k-평균 알고리즘**

**<최적의 클러스터 개수 찾기>**

**실루엣 점수(silhouette score)**  
(b-a)/max(a,b)  
a: 동일한 클러스터에 있는 다른 샘플까지 평균 거리(즉, 클러스터 내부의 평균 거리)  
b : 가장 가까운 클러스터까지 평균 거리(즉, 가장 가까운 클러스터의 샘플까지 평균 거리)  
-1 < silhouettte score < 1  
+1 에 가까우면 자신의 클러스터 안에 잘 속해 있고 다른 클러스터와는 멀리 떨어져 있다는 뜻이다.  
 0에 가까우면 클러스터 경계에 위치한다는 의미다.  
-1에 가까우면 이 샘플이 잘못된 클러스터에 할당되었다.  

**실루엣 다이어그램**  
높이 : 클러스터가 포함하고 있는 샘플의 개수  
너비 : 이 클러스터에 포함된 샘플의 정렬된 실루엣 계수  
수직 파선 : 각 클러스터 개수에 해당하는 실루엣 점수  
(한 클러스터의 샘플 대부분이 이 점수보다 낮은 계수를 가지면 클러스터의 샘플이 다른 클러스터랑 너무 가깝다는 것을 의미하므로 나쁜 클러스터이다)

###9.1.2 k-평균의 한계

1) 최적이 아닌 솔루션을 피하려면 알고리즘을 여러 번 실행 해야 함.  
2) k-평균은 클러스터의 크기나 밀집도가 서로 다르거나 원형이 아닐 경우 잘 작동하지 않는다.  

TIP: K-평균을 실행하기 전에 입력 특성의 스케일을 맞추는 것이 중요하다.  특성의 스케일을 맞추어도 모든 클러스터가 잘 구분되고 원형을 형태를 가진다고 보장할 수는 없지만 일반적으로 더 좋아진다.  

###9.1.3 군집을 사용한 이미지 분할 

##9.2 가우시안 혼합

샘플이 파라미터가 알려지지 않은 여러 개의 혼합된 가우시안 분포에서 생성되었다고 가정하는 확률 모델  
하나의 가우시안 분포에서 생성된 모든 샘플은 하나의 클러스터를 형성한다. 일반적으로 이 클러스터는 타원형이다. 

In [1]:
from sklearn.datasets import make_moons

In [2]:
X,y = make_moons(n_samples=1000,noise=0.05)

In [3]:
from sklearn.mixture import GaussianMixture

gm = GaussianMixture(n_components=3, n_init=10)
gm.fit(X)

GaussianMixture(n_components=3, n_init=10)

In [4]:
gm.weights_

array([0.58670538, 0.2051099 , 0.20818473])

In [5]:
gm.means_

array([[ 0.50371024,  0.24794041],
       [ 1.73747779, -0.07332072],
       [-0.72997963,  0.57134784]])

In [6]:
gm.covariances_

array([[[ 0.16293021, -0.09909628],
        [-0.09909628,  0.28647724]],

       [[ 0.05137427,  0.06097534],
        [ 0.06097534,  0.09019564]],

       [[ 0.05899582,  0.06527952],
        [ 0.06527952,  0.08803785]]])

In [7]:
#알고리즘 수렴 여부
gm.converged_

True

In [9]:
#알고리즘 반복 횟수
gm.n_iter_

14

In [10]:
#하드 군집
gm.predict(X)

array([1, 2, 0, 0, 2, 0, 1, 2, 2, 0, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 0, 0,
       0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 2, 2, 2, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 2, 1, 0,
       1, 2, 1, 2, 1, 1, 0, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 0, 0, 2, 0, 2,
       0, 2, 1, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 0, 1, 0, 1, 2, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 1, 2, 0, 0, 0, 2, 1, 0, 2, 0, 1,
       1, 2, 0, 2, 0, 1, 0, 0, 1, 0, 0, 1, 2, 0, 1, 2, 0, 0, 2, 2, 1, 2,
       0, 0, 2, 0, 0, 0, 1, 2, 2, 2, 0, 0, 2, 0, 0, 0, 2, 2, 2, 1, 0, 0,
       0, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0, 0, 1, 0, 1, 0, 2, 0, 0, 1, 2, 0,
       2, 2, 1, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0, 2, 1, 2, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 2, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 2, 0, 2, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 1, 0, 0, 0, 0,

In [11]:
#소프트 군집
gm.predict_proba(X)

array([[9.41383493e-004, 9.99058617e-001, 1.20886573e-195],
       [1.08999841e-001, 7.28348473e-181, 8.91000159e-001],
       [1.00000000e+000, 1.59693799e-081, 4.57488417e-019],
       ...,
       [9.95473993e-001, 4.52600674e-003, 2.55634934e-142],
       [1.00000000e+000, 1.39355850e-023, 7.73271980e-073],
       [5.62343773e-001, 4.37656227e-001, 1.04378696e-159]])

In [12]:
X_new,y_new = gm.sample(6)
X_new

array([[ 0.41958206,  0.28404294],
       [-0.43191147,  0.54708817],
       [ 0.62964201,  0.12095446],
       [ 1.65009936, -0.10012306],
       [ 1.8638079 , -0.07943128],
       [ 1.82468856,  0.02554991]])

In [13]:
y_new

array([0, 0, 0, 1, 1, 1])

In [14]:
#주어진 위치에서 모델의 밀도를 측정
#샘플이 주어지면 이 메서드는 그 위치의 확률 밀도 함수(pdf)의 로그를 예측한다.
#점수가 높을수록 밀도가 높은 것
gm.score_samples(X)

array([-9.41418610e-01, -1.08725330e+00, -1.49804937e+00, -2.20309294e+00,
       -9.07676792e-01, -1.48902288e+00, -4.83680411e-01, -1.00420809e+00,
       -7.24201675e-02, -1.29903363e+00, -1.63421698e+00, -1.61792647e+00,
       -1.55242430e+00, -5.25660111e-01, -1.33125021e+00, -8.15566258e-01,
       -1.63127192e+00, -1.81864549e+00, -1.43247005e+00, -1.75486295e+00,
       -1.32356480e+00, -2.18784357e+00, -1.94930213e+00, -5.88372735e-01,
       -2.04864943e+00, -1.55867429e+00, -2.39132377e-02, -2.01296306e+00,
       -1.73651751e+00, -1.47096646e+00, -2.06497171e+00, -1.52861618e+00,
       -3.55530360e-01, -1.13136408e+00, -1.86386693e+00, -1.39432651e+00,
       -1.45824284e+00, -1.44354958e+00, -7.44179309e-01, -2.09999318e+00,
       -1.35924178e+00, -1.75544648e+00, -7.91530548e-01, -2.16350373e+00,
       -1.89169878e+00, -1.74840169e+00, -3.90906939e-01, -1.62452405e+00,
       -1.47567690e+00, -1.52249326e+00, -9.29778517e-01, -6.16803550e-01,
       -5.23653422e-01, -

확률 밀도: 0에서 1까지의 값이 아니라 어떤 양숫값도 될 수 있다.  
샘플이 특정 지역 안에 속할 확률을 예측하려면 그 지역에 대해 PDF를 적분해야 한다.

###9.2.1 가우시안 혼합을 사용한 이상치 탐지

밀도가 낮은 지역에 있는 모든 샘플을 이상치로 볼 수 있다.  
먼저 사용할 밀도 임곗값을 정해야 한다.

In [15]:
densities = gm.score_samples(X)

In [18]:
densities.shape

(1000,)

In [21]:
import numpy as np
density_threshold = np.percentile(densities,4) #네 번째 백분위수(4%)를 밀도 임곗값으로 사용하여 이상치 구분
anomalies = X[densities < density_threshold]

In [22]:
anomalies

array([[-0.09225196,  1.08136746],
       [ 1.21195786, -0.52296265],
       [ 1.2471304 , -0.42894135],
       [ 2.01875505,  0.52685001],
       [ 1.97066436,  0.45562217],
       [ 1.14988367, -0.45620767],
       [ 1.67507679, -0.45134561],
       [ 1.89035365,  0.48929166],
       [ 1.17871217, -0.55964097],
       [-0.98647466,  0.0372289 ],
       [ 1.99939564,  0.49904357],
       [ 1.12627018, -0.56805783],
       [-0.94662748,  0.03505271],
       [ 1.12426324, -0.55677313],
       [ 0.02174227, -0.12240238],
       [ 1.10710801, -0.52728049],
       [-0.95670412,  0.03166952],
       [ 1.86803139,  0.50279363],
       [ 1.18488242, -0.48055426],
       [ 1.05127535,  0.41518824],
       [ 1.18508203, -0.38939824],
       [-0.94978927,  0.01102062],
       [ 1.9582586 ,  0.52832377],
       [ 1.19456119, -0.4864187 ],
       [ 1.94173025,  0.43963342],
       [ 1.96184324,  0.47530529],
       [ 1.99530833,  0.48909722],
       [ 1.17814834, -0.49677955],
       [ 1.18098213,

###9.2.2 클러스터 개수 선택하기

가우시안 혼합에서는 이너셔나 실루엣 점수와 같은 지표를 사용할 수 없음. 이런 지표들은 클러스터가 타원형이거나 크기가 다를 때 안정적이지 않기 떄문이다.



*   BIC = log(m)p - 2log(L^)
*   AIC = 2p - 2log(L^)



m : 샘플의 개수  
p : 모델이 학습할 파라미터 개수  
L^ : 모델의 가능도 함수(likelihood function)의 최댓값

BIC와 AIC 는 모두 학습할 파라미터가 많은(즉 클러스터가 많은) 모델에게 벌칙을 가하고 데이터에 잘 학습하는 모델에게 보상을 더한다.

In [23]:
gm.bic(X)

2763.3621428127867

In [24]:
gm.aic(X)

2679.9303030700903

###9.2.3 베이즈 가우시안 혼합 모델

최적의 클러스터 개수를 수동으로 찾지 않고 불필요한 클러스터의 가중치를 0으로 (또는 0에 가깝게) 만드는 BayesianGaussianMixture 클래스를 사용할 수 있다.

In [25]:
from sklearn.mixture import BayesianGaussianMixture
bgm = BayesianGaussianMixture(n_components=10,n_init=10)
bgm.fit(X)
np.round(bgm.weights_,2)

array([0.13, 0.14, 0.14, 0.13, 0.11, 0.15, 0.12, 0.08, 0.  , 0.  ])

알고리즘이 자동으로 8개의 클러스터가 필요하다는 것을 감지했다.