1. scikit-learn 으로부터 의사결정나무 모듈을 불러오는 코드를 아래에 작성하세요.

In [1]:
from sklearn.tree import DecisionTreeClassifier

# 셀을 실행할 때 팝업이 뜨면 `무시하고 계속하기` 를 눌러주세요
## 데이터 다운로드
--- 
아래 셀을 실행시켜 데이터를 colab에 불러옵니다.  
셀 실행은 Ctrl + Enter 를 이용해 실행 시킬 수 있습니다. 

In [2]:
# 데이터 다운로드 링크로 데이터를 코랩에 불러옵니다.

!wget 'https://bit.ly/3gLj0Q6'

import zipfile
with zipfile.ZipFile('3gLj0Q6', 'r') as existing_zip:
    existing_zip.extractall('data')

--2021-10-11 09:35:15--  https://bit.ly/3gLj0Q6
Resolving bit.ly (bit.ly)... 67.199.248.10, 67.199.248.11
Connecting to bit.ly (bit.ly)|67.199.248.10|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://drive.google.com/uc?export=download&id=1or_QN1ksv81DNog6Tu_kWcZ5jJWf5W9E [following]
--2021-10-11 09:35:15--  https://drive.google.com/uc?export=download&id=1or_QN1ksv81DNog6Tu_kWcZ5jJWf5W9E
Resolving drive.google.com (drive.google.com)... 172.217.203.102, 172.217.203.139, 172.217.203.100, ...
Connecting to drive.google.com (drive.google.com)|172.217.203.102|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://doc-0c-10-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/fnckp2r02t9pi3s7ug8cte1c7cr20vkl/1633944900000/17946651057176172524/*/1or_QN1ksv81DNog6Tu_kWcZ5jJWf5W9E?e=download [following]
--2021-10-11 09:35:15--  https://doc-0c-10-docs.googleusercontent.com/docs/secur

## 라이브러리 불러오기
---
아래 셀을 실행시켜 pandas 와 DecisionTreeClassifier 를 불러옵니다.

In [3]:
import pandas as pd
from sklearn.tree import DecisionTreeRegressor

## 데이터 불러오기
---
아래 셀을 실행시켜 csv 파일 데이터를 DataFrame 객체로 불러옵니다.

In [4]:
train = pd.read_csv('data/train.csv') 
test = pd.read_csv('data/test.csv')

## 결측치 제거하기
---
결측치를 제거하고, 결측치가 모두 제거됐는지 확인합니다.

In [5]:
test = test.dropna()
train = train.dropna()

print(train.isnull().sum())

id                        0
hour                      0
hour_bef_temperature      0
hour_bef_precipitation    0
hour_bef_windspeed        0
hour_bef_humidity         0
hour_bef_visibility       0
hour_bef_ozone            0
hour_bef_pm10             0
hour_bef_pm2.5            0
count                     0
dtype: int64


2. train 데이터중 <br>
예측해야할 `count` 피쳐를 drop()함수를 사용하고, axis=1 옵션을 사용해 해당 열을 제외한 데이터들을 `X_train` 이라는 이름의 DataFrame 객체로 만들고 <br>
`count` 피쳐만을 데이터로 갖는 `Y_train` 이라는 이름의 DataFrame 객체로 만드는 코드를 아래에 작성하세요

In [6]:
X_train = train.drop('count',axis=1)
X_train

id  hour  ...  hour_bef_pm10  hour_bef_pm2.5
0        3    20  ...           76.0            33.0
1        6    13  ...           73.0            40.0
2        7     6  ...           32.0            19.0
3        8    23  ...           75.0            64.0
4        9    18  ...           27.0            11.0
...    ...   ...  ...            ...             ...
1454  2174     4  ...           37.0            27.0
1455  2175     3  ...           34.0            19.0
1456  2176     5  ...           30.0            21.0
1457  2178    21  ...           71.0            36.0
1458  2179    17  ...           38.0            17.0

[1328 rows x 10 columns]

In [9]:
import pandas as pd
Y_train =pd.DataFrame(train['count'])
Y_train

count
0      49.0
1     159.0
2      26.0
3      57.0
4     431.0
...     ...
1454   21.0
1455   20.0
1456   22.0
1457  216.0
1458  170.0

[1328 rows x 1 columns]

3. `model` 변수명으로 모델을 선언하고, fit() 함수를 사용해서, `X_train` 을 input 으로 삼고, `Y_train` 을 output 으로 삼아 모델을 훈련시키는 코드를 아래에 작성하세요

In [10]:
model = DecisionTreeClassifier()
model.fit(X_train,Y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

4. predict() 를 이용해 test data 를 훈련된 모델로 예측한 data 를 생성하고 예측결과 상위 5개를 출력하는 코드를 작성하세요.

In [12]:
model.predict(test)[:5]

array([108., 261.,  49.,  18.,  52.])

## 데이터 다운로드 2
---
아래 셀을 실행시켜 데이터를 colab 에 불러옵니다.
셀 실행은 Ctrl + Enter 를 이용해 실행시킬 수 있습니다.

In [43]:
# 데이터 다운로드 링크로 데이터를 코랩에 불러옵니다.

!wget 'https://bit.ly/3i4n1QB'

import zipfile
with zipfile.ZipFile('3i4n1QB', 'r') as existing_zip:
    existing_zip.extractall('data')

--2021-10-11 10:31:26--  https://bit.ly/3i4n1QB
Resolving bit.ly (bit.ly)... 67.199.248.10, 67.199.248.11
Connecting to bit.ly (bit.ly)|67.199.248.10|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://drive.google.com/uc?export=download&id=1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw [following]
--2021-10-11 10:31:26--  https://drive.google.com/uc?export=download&id=1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw
Resolving drive.google.com (drive.google.com)... 172.217.203.102, 172.217.203.100, 172.217.203.138, ...
Connecting to drive.google.com (drive.google.com)|172.217.203.102|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://doc-10-10-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/o8cqu0pf6q3vjfb1m0hklrh410sa20h4/1633948275000/17946651057176172524/*/1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw?e=download [following]
--2021-10-11 10:31:27--  https://doc-10-10-docs.googleusercontent.com/docs/secur

In [44]:
# 라이브러리 불러오기

import pandas as pd
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.ensemble import RandomForestClassifier

In [45]:
train = pd.read_csv('data/train.csv')

In [46]:
train['type']

0       white
1         red
2       white
3       white
4       white
        ...  
5492    white
5493    white
5494    white
5495    white
5496    white
Name: type, Length: 5497, dtype: object

In [54]:
train

index  quality  fixed acidity  ...  sulphates  alcohol   type
0         0        5            5.6  ...       0.44     10.2  white
1         1        5            8.8  ...       0.59      9.5    red
2         2        5            7.9  ...       0.52     10.9  white
3         3        6            7.0  ...       0.50     10.8  white
4         4        6            7.8  ...       0.43     10.9  white
...     ...      ...            ...  ...        ...      ...    ...
5492   5492        5            7.7  ...       0.39     10.1  white
5493   5493        6            6.3  ...       0.51     11.0  white
5494   5494        7            7.8  ...       0.72     11.3  white
5495   5495        5            6.6  ...       0.41     10.5  white
5496   5496        6            7.0  ...       0.36      9.7  white

[5497 rows x 14 columns]

In [55]:
pd.get_dummies(train)

index  quality  fixed acidity  ...  alcohol  type_red  type_white
0         0        5            5.6  ...     10.2         0           1
1         1        5            8.8  ...      9.5         1           0
2         2        5            7.9  ...     10.9         0           1
3         3        6            7.0  ...     10.8         0           1
4         4        6            7.8  ...     10.9         0           1
...     ...      ...            ...  ...      ...       ...         ...
5492   5492        5            7.7  ...     10.1         0           1
5493   5493        6            6.3  ...     11.0         0           1
5494   5494        7            7.8  ...     11.3         0           1
5495   5495        5            6.6  ...     10.5         0           1
5496   5496        6            7.0  ...      9.7         0           1

[5497 rows x 15 columns]

In [7]:
# Scailing
scaler = MinMaxScaler()
scaler.fit(train[['fixed acidity']])
train['Scaled fixed acidity'] = scaler.transform(train[['fixed acidity']])

In [53]:
train.dtypes

index                     int64
quality                   int64
fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
type                     object
dtype: object

In [9]:
# Encoding
encoder = OneHotEncoder()
encoder.fit(train[['type']])
onehot = encoder.transform(train[['type']])

In [10]:
onehot

<5497x2 sparse matrix of type '<class 'numpy.float64'>'
	with 5497 stored elements in Compressed Sparse Row format>

In [11]:
onehot = onehot.toarray()
onehot

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [13]:
onehot = pd.DataFrame(onehot)
onehot

0    1
0     0.0  1.0
1     1.0  0.0
2     0.0  1.0
3     0.0  1.0
4     0.0  1.0
...   ...  ...
5492  0.0  1.0
5493  0.0  1.0
5494  0.0  1.0
5495  0.0  1.0
5496  0.0  1.0

[5497 rows x 2 columns]

In [15]:
onehot.columns = encoder.get_feature_names()
onehot.columns

Index(['x0_red', 'x0_white'], dtype='object')

In [16]:
train = pd.concat([train, onehot], axis = 1)
train

index  quality  fixed acidity  ...  Scaled fixed acidity  x0_red  x0_white
0         0        5            5.6  ...              0.148760     0.0       1.0
1         1        5            8.8  ...              0.413223     1.0       0.0
2         2        5            7.9  ...              0.338843     0.0       1.0
3         3        6            7.0  ...              0.264463     0.0       1.0
4         4        6            7.8  ...              0.330579     0.0       1.0
...     ...      ...            ...  ...                   ...     ...       ...
5492   5492        5            7.7  ...              0.322314     0.0       1.0
5493   5493        6            6.3  ...              0.206612     0.0       1.0
5494   5494        7            7.8  ...              0.330579     0.0       1.0
5495   5495        5            6.6  ...              0.231405     0.0       1.0
5496   5496        6            7.0  ...              0.264463     0.0       1.0

[5497 rows x 17 columns]

In [17]:
train = train.drop(columns = ['type'])
train

index  quality  fixed acidity  ...  Scaled fixed acidity  x0_red  x0_white
0         0        5            5.6  ...              0.148760     0.0       1.0
1         1        5            8.8  ...              0.413223     1.0       0.0
2         2        5            7.9  ...              0.338843     0.0       1.0
3         3        6            7.0  ...              0.264463     0.0       1.0
4         4        6            7.8  ...              0.330579     0.0       1.0
...     ...      ...            ...  ...                   ...     ...       ...
5492   5492        5            7.7  ...              0.322314     0.0       1.0
5493   5493        6            6.3  ...              0.206612     0.0       1.0
5494   5494        7            7.8  ...              0.330579     0.0       1.0
5495   5495        5            6.6  ...              0.231405     0.0       1.0
5496   5496        6            7.0  ...              0.264463     0.0       1.0

[5497 rows x 16 columns]

In [18]:
train.head()

index  quality  fixed acidity  ...  Scaled fixed acidity  x0_red  x0_white
0      0        5            5.6  ...              0.148760     0.0       1.0
1      1        5            8.8  ...              0.413223     1.0       0.0
2      2        5            7.9  ...              0.338843     0.0       1.0
3      3        6            7.0  ...              0.264463     0.0       1.0
4      4        6            7.8  ...              0.330579     0.0       1.0

[5 rows x 16 columns]

In [17]:
onehot

x0_red  x0_white
0        0.0       1.0
1        1.0       0.0
2        0.0       1.0
3        0.0       1.0
4        0.0       1.0
...      ...       ...
5492     0.0       1.0
5493     0.0       1.0
5494     0.0       1.0
5495     0.0       1.0
5496     0.0       1.0

[5497 rows x 2 columns]

5. sklearn에 model_selection 부분 속 KFold를 불러와보세요

In [19]:
from sklearn.model_selection import KFold

6. KFold에 n_splits = 5, shuffle = True, random_state = 0이라는 인자를 추가해 "kf"라는 변수에 저장해보세요

In [20]:
kf = KFold(n_splits=5,shuffle=True,random_state = 0)

7. 반복문을 통해서 1번부터 5번까지의 데이터에 접근해보세요 (추가문제입니다. 꼭 풀 필요는 없되 답지를 참고해주세요.)

In [41]:
import numpy as np
train_1 = train.to_dict('list')
features = np.array(list(train_1.values()))
features

array([[0.00000000e+00, 1.00000000e+00, 2.00000000e+00, ...,
        5.49400000e+03, 5.49500000e+03, 5.49600000e+03],
       [5.00000000e+00, 5.00000000e+00, 5.00000000e+00, ...,
        7.00000000e+00, 5.00000000e+00, 6.00000000e+00],
       [5.60000000e+00, 8.80000000e+00, 7.90000000e+00, ...,
        7.80000000e+00, 6.60000000e+00, 7.00000000e+00],
       ...,
       [1.48760331e-01, 4.13223140e-01, 3.38842975e-01, ...,
        3.30578512e-01, 2.31404959e-01, 2.64462810e-01],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00]])

In [29]:
from sklearn.datasets import load_iris
iris = load.iris()
features = iris.data

NameError: ignored

In [22]:
n_iter = 0


for train_index, test_index in kf.split(train):
    X_train,X_test = train[train_index],train[test_index]
    y_train,y_test = onehot[train_index],onehot[test_index]

    kf.fit(X_train,y_train)
    pred = kf.predict(X_test)
    n_iter +=1

KeyError: ignored